#Directories
WORK_DIR = "/media/pgt/New_Space/Leandro/"
DATA_DIR = WORK_DIR + "data/"
PIPE_V1 = WORK_DIR + "pipeline/"

IDX_DIR = PIPE_V1 + "index/"
FASTP_DIR = PIPE_V1 + "FASTP/"
STAR_DIR = PIPE_V1 + "STAR/"
SCALLOP_DIR = PIPE_V1 + "SCALLOP"
GTF_DIR = PIPE_V1 + "GTF/"
# TACO_DIR = PIPE_V1 + "TACO_output/"
STRINGTIE_OUT = PIPE_V1 + "STRINGTIE_MERGE/"
GTF_TO_FASTA = PIPE_V1 + "GTF_FASTA/"

FEELNC_DIR = PIPE_V1 + "FEELNC/"
FEELNC_FILTER = FEELNC_DIR + "FILTER/"
FEELNC_CODPOT = FEELNC_DIR + "CODPOT/"
FEELNC_CLASSIFIER = FEELNC_DIR + "CLASSIFIER/"

SALMON_DIR = PIPE_V1 + "SALMON"
SALMON_INDEX = SALMON_DIR + "/gencode.v31.transcripts.index"

#Samples
SAMPLES = ['R2809_D2A01ACXX_TAATGCGC_L005_', 'R2810_C00JVACXX_CGATGT_L001_',
           'R2816_C0GTHACXX_ACTGAT_L007_', 'R2826_C00JVACXX_TGACCA_L001_',
           'R2835_C0JYLACXX_TGACCA_L004_']

#index
GENOME_FILE = DATA_DIR + "GRCh38.p12.genome.fa"
GTF = DATA_DIR + "gencode.v31.annotation.gtf"
PC = DATA_DIR + "gencode.v31.pc_transcripts.fa"
LNCRNA = DATA_DIR + "gencode.v31.long_noncoding_RNAs.gtf"
TRANSCRPT = DATA_DIR + "gencode.v31.transcripts.fa"

#Log
LOGS = PIPE_V1 + "LOGS/"
FASTP_LOG = LOGS + "FASTP_LOG/"

#BENCHMARK
BENCHMARK_DIR = PIPE_V1 + "BENCHMARK"
